version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pwd
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.5.0
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres_user:postgres_pwd@postgres:5432/airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "
      airflow db init &&
      airflow webserver"
    depends_on:
      - postgres
      - airflow-scheduler

  airflow-scheduler:
    image: apache/airflow:2.5.0
    volumes:
      - ./dags:/opt/airflow/dags
    command: airflow scheduler
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres_user:postgres_pwd@postgres:5432/airflow

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.0.0
    volumes:
      - ./dbt:/usr/app/dbt
    depends_on:
      - postgres
    environment:
      - DBT_PROFILES_DIR=/usr/app/dbt/profiles
      - DBT_PROJECT_DIR=/usr/app/dbt

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data

volumes:
  postgres_data:
  minio_data:
